source 'https://rubygems.org'

gem 'calabash-cucumber', '~> 0.16.4'
gem 'run_loop', '~> 1.5.6'
gem 'rubyzip'
gem 'syntax'
gem 'yard-cucumber'
gem 'selenium-webdriver'
gem 'spec'
gem 'AXElements', '~> 7.0.0.Pre'
gem 'plist'
gem 'colorize'
gem 'zip-zip'
gem 'emoji_data'
