source 'https://github.com/CocoaPods/Specs.git'

target 'HPPhotoPrint', :exclusive => true do
  pod "HPPhotoPrint", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HPPhotoPrint", :path => "../"
end
