source 'https://github.com/CocoaPods/Specs.git'

target 'MobilePrintSDK', :exclusive => true do
  pod "MobilePrintSDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MobilePrintSDK", :path => "../"
  pod "OCMock"
end
